# Errors in pattern matching functions

func() ->
  x.call(x: y, z)

